### ISSUE TITLE
Request for a giphy

### ISSUE THREAD

**Issue by timeowilliams** [eimaam/react-next-toast#4]
Would like to see a small giphy that shows how this would look like in it's base state in my application in the README

Thanks

**Comment by eimaam** [comment]
Updated pushed! 

Added: 
> Giphy preview (as requested) - with all the supported Toast types - Success, Error, Info & Warning 
> Codesandbox Environment - Deployed Page to show the package in action + code implementation. 

Thank you for opening this issue.
